application: yakin-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: lxml
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /api/v1/points/blog
  static_files: blog_points.json
  upload: blog_points.json

- url: /api/v1/points/photo
  static_files: photo_points.json
  upload: photo_points.json

- url: /api/v1/points/tracker
  static_files: tracker_points.json
  upload: tracker_points.json

- url: /api/v1/points/video
  static_files: video_points.json
  upload: video_points.json

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: .*
  script: main.app

inbound_services:
- warmup
