application: mongolrally-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

- url: .*
  script: main.app

inbound_services:
- warmup