application: yakin-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: lxml
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /api/v1/points/tracker
  static_files: tracker_points.json
  upload: tracker_points.json

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: .*
  script: tracker.app

inbound_services:
- warmup
